<?php
/**
* Implements hook_enable().
*/
function my_module_enable() {
  variable_set('admin_theme', 'seven');
  variable_set('clean_url', TRUE);
  variable_set('comment_page', 0);
  variable_set('cron_key', 'zIOgaxCCAwACJ7n3DlykURdPF0efOSSI5rPLqkIhGZE');
  variable_set('cron_last', 1392065631);
  variable_set('css_js_query_string', 'n0lgf1');
  variable_set('date_default_timezone', 'Europe/Berlin');
  variable_set('drupal_http_request_fails', FALSE);
  variable_set('drupal_private_key', 'AQEWoD1oKQ57tRrardIOjcsOEm2DCQZvjCRFTT4fmQQ');
  variable_set('features_ignored_orphans', array());
  variable_set('file_temporary_path', '/Applications/MAMP/tmp/php');
  variable_set('filter_fallback_format', 'plain_text');
  variable_set('install_profile', 'standard');
  variable_set('install_task', 'done');
  variable_set('install_time', 1387314357);
  variable_set('menu_expanded', array());
  variable_set('menu_masks', array(
  501,
  493,
  250,
  247,
  246,
  245,
  125,
  123,
  122,
  121,
  117,
  63,
  62,
  61,
  60,
  59,
  58,
  44,
  31,
  30,
  29,
  28,
  27,
  24,
  21,
  15,
  14,
  13,
  11,
  7,
  6,
  5,
  3,
  2,
  1,
));
  variable_set('node_admin_theme', '1');
  variable_set('node_options_page', array(
  'status',
));
  variable_set('node_submitted_page', FALSE);
  variable_set('path_alias_whitelist', array());
  variable_set('site_default_country', '');
  variable_set('site_mail', 'admin@example.com');
  variable_set('site_name', 'Drupal');
  variable_set('theme_default', 'bartik');
  variable_set('update_last_check', 1392052414);
  variable_set('update_last_email_notification', 1392052401);
  variable_set('update_notify_emails', array(
  'admin@example.com',
));
  variable_set('user_admin_role', '3');
  variable_set('user_pictures', '1');
  variable_set('user_picture_dimensions', '1024x1024');
  variable_set('user_picture_file_size', '800');
  variable_set('user_picture_style', 'thumbnail');
  variable_set('user_register', 2);
  variable_set('404_fast_paths_exclude', '/\/(?:styles)\//');
  variable_set('404_fast_paths', '/\.(?:txt|png|gif|jpe?g|css|js|ico|swf|flv|cgi|bat|pl|dll|exe|asp)$/i');
  variable_set('404_fast_html', '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "@path" was not found on this server.</p></body></html>');
}
